name: Build

on:
  push:
    paths:
      - '.github/workflows/build.yml'
  pull_request:
    paths:
      - '.github/workflows/build.yml'
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Clone source repository
        run: |
          git clone \
          --recursive \
          --single-branch \
          --branch winlator-tiger \
          https://github.com/on-that-tiger-mountain/winlator-app

      - name: Checkout build repository
        uses: actions/checkout@v6
        with:
          path: build

#      - name: Remove sharedUserId
#        run: |
#          cd winlator/app/src/main
#          sed -i 's/android:sharedUserId="com.termux"//' AndroidManifest.xml

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: 'cmake;3.22.1'

      - name: Fix ALL duplicate native libs
        run: |
          find . -name "build.gradle" -exec sed -i '/android {/a \    packagingOptions { jniLibs { pickFirsts += ["lib/arm64-v8a/*.so"] } }' {} +
          echo "Fixed all .so duplicate issues"

      - name: Build APK
        run: |
          GRADLEW_PATH=$(find . -name gradlew | head -n 1)
          PROJECT_ROOT=$(dirname "$GRADLEW_PATH")
          cd "$PROJECT_ROOT"
          chmod +x gradlew
          ./gradlew assembleDebug --stacktrace

      - name: Get current source commit SHA and changelog
        run: |
          cd winlator-app
          if [ -f ../build/commit_sha.txt ]; then
            echo "$(git log --pretty=format:%s $(cat ../build/commit_sha.txt)..HEAD)" > CHANGELOG.txt
            git rev-parse HEAD > ../build/commit_sha.txt
          else
            git rev-parse HEAD > ../build/commit_sha.txt
            echo "$(git log --pretty=format:%s $(cat ../build/commit_sha.txt)..HEAD)" > CHANGELOG.txt
          fi

      - name: Update last build commit SHA
        run: |
          cd build
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add commit_sha.txt
          git commit -m "Update last build commit SHA" || true
          git push

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: winlator-app/CHANGELOG.txt
          files: winlator-app/app/build/outputs/apk/debug/app-debug.apk
          name: winlator-tiger-${{ env.DATE }}
          tag_name: ${{ env.DATE }}
